<a href="https://colab.research.google.com/github/hetmangukiya32/Data-Science-and-Machine-Learning/blob/main/01-Python/Numpy/Basic/basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Numpy***

In [1]:
import numpy as np
# numpy version
print(np.__version__)

2.0.2


In [2]:
# 2. Creating Arrays
arr1 = np.array([10, 20, 30, 40, 50])  #List

print(arr1)

arr2 = np.array((1, 2, 3, 4))           #tuple

print(arr2)

arr3 = np.array([[1, 2], [3, 4]])

print(arr3)

arr4 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr4)

[10 20 30 40 50]
[1 2 3 4]
[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]]


In [3]:
#3.Array Dimensions
a = np.array(10)

print(a.ndim)

b = np.array([1,2,3,4])

print(b.ndim)

c = np.array([
    [1,2],
    [3,4]
])

print(c.ndim)

d = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])

print(d.ndim)


0
1
2
3


In [4]:
# 4.Data Types
arr = np.array([1,2,3])
print(arr.dtype)

arr = np.array([1.2,2.5,3.6])
print(arr.dtype)

arr = np.array(["Apple","Banana"])
print(arr.dtype)

arr = np.array([True,False])
print(arr.dtype)

#U6 = Unicode string



int64
float64
<U6
bool


In [5]:
# Specify datatype

arr = np.array([1,2,3],dtype='float')

print(arr)
print(arr.dtype)


[1. 2. 3.]
float64


In [9]:
# 5. Shape and size and itemsize and nbytes

arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr.shape)
print(arr.size)
print(arr.itemsize)
print(arr.nbytes)

(2, 3)
6
8
48


In [11]:
# 9. Indexing (1D)
arr = np.array([10,20,30,40,50])

print(arr[0])

print(arr[2])

print(arr[-1])

10
30
50


In [12]:
#  Indexing (2D)

arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr[0,0])

print(arr[0,2])

print(arr[1,1])

print(arr[1,2])

1
3
5
6


In [13]:
# Indexing (3D)

arr = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])

print(arr[0,0,0])

print(arr[0,1,1])

print(arr[1,0,1])

print(arr[1,1,0])


1
4
6
7


In [14]:
  # Slicing (1D)


arr = np.array([10,20,30,40,50,60])

print(arr[1:4])

print(arr[:3])

print(arr[2:])

print(arr[-3:])

print(arr[::2])


[20 30 40]
[10 20 30]
[30 40 50 60]
[40 50 60]
[10 30 50]


In [15]:
  # Slicing (2D)
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr[:,1])

print(arr[1,:])

print(arr[0:2,1:3])

print(arr[:,0:2])

[2 5 8]
[4 5 6]
[[2 3]
 [5 6]]
[[1 2]
 [4 5]
 [7 8]]


In [17]:
# Copy Array

arr = np.array([1,2,3])

copy_arr = arr.copy()

copy_arr[0] = 100

print(arr)

print(copy_arr)


[1 2 3]
[100   2   3]


In [18]:
#View Array

arr = np.array([1,2,3])

view_arr = arr.view()

view_arr[0] = 500

print(arr)

print(view_arr)

[500   2   3]
[500   2   3]


In [19]:
# 1. Reshape
arr = np.array([1,2,3,4,5,6])

print(arr.reshape(2,3))
print(arr.reshape(3,2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [20]:
# 2. Flatten
arr = np.array([
    [1,2,3],
    [4,5,6]
])

flat = arr.flatten()

print(flat)

[1 2 3 4 5 6]


In [21]:
#Ravel
arr = np.array([
    [10,20],
    [30,40]
])

rav = arr.ravel()

print(rav)

# ravel()	                flatten()
# Returns a view	        Returns a copy
# Shares memory	          Creates new memory
# Faster	                Slightly slower
# Changes                 may affect original

[10 20 30 40]


In [22]:
# 4. Resize

arr = np.array([1,2,3,4])

arr.resize((2,2))

print(arr)

[[1 2]
 [3 4]]


In [23]:
# Transpose
arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [24]:
# Arithmetic Operations

a = np.array([10,20,30])
b = np.array([1,2,3])

print("Addition")
print(a+b)

print("Subtraction")
print(a-b)

print("Multiplication")
print(a*b)

print("Division")
print(a/b)

print("Power")
print(a**2)

print("Modulus")
print(a%b)

Addition
[11 22 33]
Subtraction
[ 9 18 27]
Multiplication
[10 40 90]
Division
[10. 10. 10.]
Power
[100 400 900]
Modulus
[0 0 0]


In [25]:
# 7. Scalar Operations

arr = np.array([10,20,30])

print(arr+5)
print(arr-5)
print(arr*2)
print(arr/2)

[15 25 35]
[ 5 15 25]
[20 40 60]
[ 5. 10. 15.]


In [26]:
# Universal Functions (ufunc)


arr = np.array([1,4,9,16,25])

print(np.sqrt(arr))

print(np.square(arr))

print(np.abs([-2,-8,10]))

print(np.exp([1,2]))

print(np.log([1,2,10]))

[1. 2. 3. 4. 5.]
[  1  16  81 256 625]
[ 2  8 10]
[2.71828183 7.3890561 ]
[0.         0.69314718 2.30258509]


In [27]:
# Trigonometric Functions

angle = np.array([0,30,45,60,90])

radian = np.radians(angle)

print(np.sin(radian))

print(np.cos(radian))

print(np.tan(radian))

[0.         0.5        0.70710678 0.8660254  1.        ]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [29]:
#  Rounding Functions

arr = np.array([1.2,2.7,3.5,4.8])

print(np.floor(arr))

print(np.ceil(arr))

print(np.round(arr))

[1. 2. 3. 4.]
[2. 3. 4. 5.]
[1. 3. 4. 5.]


In [30]:
# Comparison Operators


arr = np.array([10,20,30,40])

print(arr>20)

print(arr<30)

print(arr==20)

[False False  True  True]
[ True  True False False]
[False  True False False]


In [31]:
# Broadcasting

a = np.array([
    [1],
    [2],
    [3]
])

b = np.array([10,20,30])

print(a+b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [32]:
# Broadcasting Example


arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr+100)


[[101 102 103]
 [104 105 106]]


In [33]:
# Mathematical Functions


arr = np.array([10,20,30])

print(np.max(arr))

print(np.min(arr))

print(np.sum(arr))

print(np.prod(arr))

print(np.mean(arr))


30
10
60
6000
20.0


In [34]:
#  Zeros


arr = np.zeros((2,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [35]:
# Ones


arr = np.ones((3,2))

print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [36]:
# Empty


arr = np.empty((2,2))

print(arr)

[[4.9e-323 9.9e-323]
 [1.5e-322 2.0e-322]]


In [37]:
# Arange


print(np.arange(10))

print(np.arange(1,11))

print(np.arange(0,20,2))

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10 12 14 16 18]


In [38]:
#  Linspace


print(np.linspace(0,10,5))

print(np.linspace(1,100,10))


[ 0.   2.5  5.   7.5 10. ]
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [39]:
#  Identity Matrix

print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [40]:
#  Eye Matrix


print(np.eye(4))
# Creates a 4 × 4 identity matrix.
#    1 is placed on the diagonal.
#      All other values are 0.

print(np.eye(3,4))
# Creates a 3 × 4 matrix.
#   It has 3 rows and 4 columns.
#     1 is placed on the diagonal until the rows end.

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
