<a href="https://colab.research.google.com/github/hetmangukiya32/Data-Science-and-Machine-Learning/blob/main/01-Python/Numpy/random%20value/random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Random Module
The NumPy Random Module is used to generate random numbers.

It is commonly used in:

Machine Learning
Data Science
Simulations
Testing

In [42]:
import numpy as np
print(np.random.rand())

0.5632614255294128


In [44]:
#Multiple values
print(np.random.rand(2,3))

[[0.65374965 0.19664676 0.88364389]
 [0.67703148 0.98311396 0.20333012]]


In [46]:
# randn()

# Generates random numbers from the standard normal distribution.
# Mean = 0
# Standard Deviation = 1
print(np.random.randn(3))

[ 0.70498978 -0.39742621 -0.72267645]


In [49]:
##genrate random integers
print(np.random.randint(1,10))
print(np.random.randint(1,10,size=(2,3)))

5
[[5 8 9]
 [7 2 3]]


In [50]:
# random()
# Returns random float numbers between 0 and 1.
print(np.random.random())

0.8539251957147599


In [51]:
# choice()
# Selects a random value from a list.

arr = ["Apple", "Banana", "Mango"]

print(np.random.choice(arr))

Banana


In [54]:
# seed()
# Produces the same random numbers every time.

np.random.seed(10)

print(np.random.randint(1,100))

10


In [56]:
# shuffle()
# Shuffles the original array.

arr = np.array([1,2,3,4,5])
np.random.shuffle(arr)

print(arr)

[5 3 2 1 4]


In [ ]:
# permutation()
# Returns a shuffled copy of the array.

arr = np.array([1,2,3,4,5])

x = np.random.permutation(arr)

print(arr)
print(x)

In [57]:
# Sort
# np.sort() sorts the array in ascending order.

arr = np.array([5, 2, 8, 1])

print(np.sort(arr))

[1 2 5 8]


In [58]:
arr = np.array([[3,1],[4,2]])

print(np.sort(arr))
##By default row wise sorting

[[1 3]
 [2 4]]


In [59]:
# Search
# np.where() finds the index of matching values.

arr = np.array([10,20,30,20,40])

print(np.where(arr == 20))

(array([1, 3]),)


In [60]:
#search even numnbers

arr = np.array([1,2,3,4,5,6])
print(np.where(arr % 2 == 0))

(array([1, 3, 5]),)


In [61]:
# Filter
# Filtering means selecting values based on a condition.

arr = np.array([10,20,30,40,50])

x = arr[arr > 25]

print(x)

[30 40 50]


In [62]:
# Filter Even Numbers
arr = np.array([1,2,3,4,5,6])
x = arr[arr % 2 == 0]

print(x)

[2 4 6]
